### ISSUE TITLE
decrease allocated memory used by cuckoohash_map

### ISSUE THREAD

**Issue by krsvital** [efficient/libcuckoo#106]
i has sqlite3 database with more then 7 millons rows;
and i need to place it to hash table

typedef cuckoohash_map<std::string,float> TS;
TS tsFiles;

 sql = "SELECT NAME,DURATION from TS_FILES;";

 rc = sqlite3_prepare(db, sql, -1, &stmt, NULL);

 if( rc == SQLITE_OK ) {
       while (sqlite3_step(stmt) == SQLITE_ROW){
             std::string *name = new std::string((const char*)sqlite3_column_text(stmt, 0));
              std::string *dur = new std::string((const char*)sqlite3_column_text(stmt, 1));

               float d;

                try{
                    d = boost::lexical_cast<float>(*dur);
                 }
                 catch(std::exception &e){
                  d = 6.00;
                }

                 tsFiles.insert(*name, d);

                  delete name;
                  delete dur;
      }
 }

after that process begin to use ~ 1g memory

can i change std::string data in key of cuckoohash_map to const char* ? or is there any other way to reduce the memory used?

**Comment by manugoyal** [comment]
Hey there! I'm not completely sure about the specifics of your workload, but if you're inserting 7 million strings, it's certainly possible the table memory usage could grow to around 1GB. It depends on the size of your strings. `const char*` could lower the memory footprint, because I think `std::string` stores a few integers to keep track of the length and capacity of the string. But it probably depends on how large your strings are on average.

Closing this for now, but please feel free to reopen if you have more questions!
