### ISSUE TITLE
Free memory on clear() and shrinking

### ISSUE THREAD

**Issue by Burning-Daylight** [efficient/libcuckoo#13]
At the moment the hashmap can only increase its memory consumption. Would it be possible to release allocated memory when the size() decreases or when clear() is called?

**Comment by manugoyal** [comment]
I just pushed a commit which lets `resize` and` rehash` decrease the size of the table. It's probably better that the user explicitly decrease the size of the table, because people won't always want the table capacity to decrease after a clear or deleting a bunch of elements. Would this work for you?

**Comment by Burning-Daylight** [comment]
Great! Thanks a lot! For me this is a perfect solution. One should take into account that this is different from the std::unordered_map behaviour, as every erase may shrink the map according to the spec, even though I don't like it this way.

**Comment by Burning-Daylight** [comment]
I tested the new feature and it seems, there is a bug - shrinking never occurs because whenever cuckoo_expand_simple(n) is called with n<ti->hashpower_, function returns before shrinking https://github.com/efficient/libcuckoo/blob/master/src/cuckoohash_map.hh#L1677

**Comment by manugoyal** [comment]
Ah I see. I think the best thing to do is to add an argument to
cuckoo_expand_simple to specify when we want to shrink and when we want to
expand.

-Manu

**Comment by manugoyal** [comment]
Okay, should be fixed now.
