### ISSUE TITLE
cuckoohash_map.reserve() greater than DEFAULT_SIZE allocates new array without freeing old(?)

### ISSUE THREAD

**Issue by tewarfel** [efficient/libcuckoo#17]
Thank you for the quick resolution on the prior issue.  Poking around, I'm finding one other concern regarding memory allocation and freeing when the # bucket entries needed is larger than the existing allocation.

Looking at examples/count_freq.cc and src/cuckoohash_map.hh:
If I modify the cuckoohash_map constructor to print out when it is allocating,  
```C++
explicit cuckoohash_map(size_t n = DEFAULT_SIZE) {
        const size_t hp = reserve_calc(n);
        TableInfo* ptr = get_tableinfo_allocator().allocate(1);
        try {
		fprintf(stderr,"Calling cuckoohash_map with hp %ld\n", hp);  fflush(stderr); // add this line
            get_tableinfo_allocator().construct(ptr, hp);
            table_info.store(ptr);
        } catch (...) {
            get_tableinfo_allocator().deallocate(ptr, 1);
            throw;
        }
    }
```
and TableInfo() constructor and destructor to show when it is allocating and freeing,
```C++
 TableInfo(const size_t hp)
            : hashpower(hp), buckets(hashsize(hp)),
              num_inserts(kNumCores(), 0), num_deletes(kNumCores(), 0) { 
	      fprintf(stderr,"allocating 2^ %ld buckets\n", hashpower); fflush(stderr); // add this line
              }

        TableInfo(const TableInfo&) = delete;
        TableInfo(TableInfo&&) = delete;

        ~TableInfo() {
	      fprintf(stderr,"de-allocating table with 2^ %ld buckets\n", hashpower); fflush(stderr); // add this line
              }
```
Then running the count_freq.cc example, I get:
Calling cuckoohash_map with hp 16
allocating 2^ 16 buckets
Calling cuckoohash_map with hp 22
allocating 2^ 22 buckets
2373133380 occurred 3 times.
Table size: 9988385
Bucket count: 4194304
Load factor: 0.595354
de-allocating table with 2^ 22 buckets
de-allocating table with 2^ 16 buckets

It seems as though the initial allocation of 2^16 buckets (DEFAULT_SIZE) doesn't get freed until _after_ the larger allocation gets freed at the end.

If I modify the count_freq.cc map to allocate the full amount needed in the allocation:
```C++
int main() {
    Table freq_map(total_inserts);
    freq_map.reserve(total_inserts);
```
...then I just see one allocation and one deallocation (as expected):
Calling cuckoohash_map with hp 22
allocating 2^ 22 buckets
4255206843 occurred 4 times.
Table size: 8740950
Bucket count: 4194304
Load factor: 0.521001
de-allocating table with 2^ 22 buckets

However, if I comment out the "reserve" line altogether, and leave the Table declaration alone:
```C++ 
int main() {
    Table freq_map;
    //freq_map.reserve(total_inserts);
```
...then I get: 
Calling cuckoohash_map with hp 16
allocating 2^ 16 buckets
Calling cuckoohash_map with hp 17
allocating 2^ 17 buckets
Calling cuckoohash_map with hp 18
allocating 2^ 18 buckets
de-allocating table with 2^ 16 buckets
Calling cuckoohash_map with hp 19
allocating 2^ 19 buckets
de-allocating table with 2^ 17 buckets
Calling cuckoohash_map with hp 20
allocating 2^ 20 buckets
de-allocating table with 2^ 18 buckets
Calling cuckoohash_map with hp 21
allocating 2^ 21 buckets
de-allocating table with 2^ 19 buckets
Calling cuckoohash_map with hp 22
allocating 2^ 22 buckets
de-allocating table with 2^ 20 buckets
2975383928 occurred 3 times.
Table size: 9988404
Bucket count: 4194304
Load factor: 0.595355
de-allocating table with 2^ 22 buckets
de-allocating table with 2^ 21 buckets

I see the (expected) automatic re-allocations occurring, but the older (too-small) allocations don't seem to be getting freed until the yet-next-larger size is re-re-allocated.  Freeing always seems to lag re-allocating by an extra steps, seemingly resulting in a lot of extra memory left allocated when the arrays get big and need to dynamically resize.  

Is there an explicit call that I should be making or testing to ensure the all the old allocations are freed once the new allocation is made and the old has been copied?

**Comment by manugoyal** [comment]
So the reason we can't immediately free the old table during expansion time is that other threads may be running at the same time, and may be reading from that old table. If we free it in the expansion thread, the other threads could read invalid memory, when they resume. You'll see in the `snapshot_and_lock_*` methods, that we retry the whole thing if the `table_info` pointer changed before and after taking locks, but even still, we can't risk taking locks on a free'd `TableInfo`.

Therefore, we add the old table to a backlog, and try deleting it during resize, when no thread's hazard pointer is set to the old table.

That being said, we should be freeing the old table if there is no other thread looking at the table. We were not doing this, because the hazard pointer of the expansion thread was set to the old table, but I just pushed a commit (https://github.com/efficient/libcuckoo/commit/c87c1937e092050915674eee05434497bcfe18b3), that fixes this.

Now you should see in the unmodified `count_freq`:
Calling cuckoohash_map with hp 16
allocating 2^ 16 buckets
Calling cuckoohash_map with hp 22
allocating 2^ 22 buckets
de-allocating table with 2^ 16 buckets
...
de-allocating table with 2^ 22 buckets

Thanks for investigating!
