### ISSUE TITLE
How to pass parameters to upsert if the value is a class poiter?

### ISSUE THREAD

**Issue by domino-succ** [efficient/libcuckoo#70]
The `state_table_` is `cuckoohash<std::string, StateCounter*>`. Note **the value is a pointer** `StateCounter*`. Can I pass the there parameters to `StateCounter*` as below? If not, how can I pass those parameters? 

```
void StateTableIncrease(std::string& key, int queue_id, int inc = 1) {
    auto inc_fn = [queue_id, inc](StateCounter* counter) {
        counter->Inc(queue_id, inc);
    };
    state_table_.upsert(key, inc_fn, queue_counts_, queue_id, inc);
  }
```

The constructor of `StateCounter` is like this: 
```
    StateCounter(int queue_num, int queue_no, int inc)
        : queue_counter(new std::vector<int>(queue_num)) {
      std::cout << "in construction of state counter" << std::endl;
      queue_counter->at(queue_no) = inc;
    }
```

**Comment by domino-succ** [comment]
@manugoyal Any thought?

**Comment by manugoyal** [comment]
Since your value type is `StateCounter*`, the table will try to construct pointers, not actual instances of `StateCounter`. Depending on your application, it might make sense to use values of type `StateCounter*`, which would generally imply that the table is not the owner of the data. But if the table does own the data, it would make a lot more sense to use `StateCounter` directly as the value type, and then call the `StateCounter` constructor accordingly.

If you must have a pointer value type and still call the normal `StateCounter` constructor, I'd suggest creating a wrapper class (in the same way I described in one of our previous conversations), which constructs a pointer using the arguments to the `StateCounter` constructor.

**Comment by domino-succ** [comment]
@manugoyal Thanks for your reply. One quick question:

If I use `StateCounter` directly as the value type instead of the pointer, is the performance the same? I guess you use `CAS` to do thread-safe. Is that the same for `StateCounter` and `StateCounter*`?

**Comment by manugoyal** [comment]
Yeah performance will be the same, maybe slightly better since the StateCounter will be stored inline, so it'll be one less memory indirection away. Thread safety is maintained through locks on individual buckets, so no two threads can access the same piece of data at the same time.

**Comment by domino-succ** [comment]
Got you. I think I'll use StateCounter as the value type. You can close this question. Thanks!

**Comment by domino-succ** [comment]
@manugoyal I found another issue. If I use `StateCounter` as the value type, `find` will return the whole StateCounter, which will be very expensive comparing to pointer as the value type.
