### ISSUE TITLE
Hash grid memory consumption / construction

### ISSUE THREAD

**Issue by tbiedert** [efficient/libcuckoo#91]
Hi,

I'm using a hash map to construct a so called hash grid for nearest neighbor queries. (For my test cases this is typically faster than a nanoflann kd-tree).
The idea is that each point `p` is placed in a bucket using `glm::ivec3(glm::floor((1.0f / r) * p))`, where `r` is the bucket size. This bucket index is used as key in a hash map, which stores the indices of the points within each bucket.

I'm trying to migrate from a sequential `QHash`-based implementation to libcuckoo for parallel grid construction.  However, for my 170 million points data set the memory consumption explodes.
The sequential implementation requires approx. 5GB RAM (total, including system etc) with 15s construction time, whereas the prototypical libcuckoo implementation causes full consumption of 32 GB RAM + 230 GB swap (SSD-based) and still is not finished.

I assume there are some toggles/tunables I should adjust.  Any help would be greatly appreciated!

Thanks in advance!

Here's my complete sequential implementation:
```
inline glm::ivec3 getBucket(const glm::vec3& p, float r) const
{
    return glm::ivec3(glm::floor((1.0f / r) * p));
}

inline uint bucketKey(const glm::ivec3& bucket) const
{
    std::hash<glm::ivec3> hasher;
    return hasher(bucket);
}

QHash<uint, std::vector<uint32_t>> buckets;

HashGrid::HashGrid(const glm::vec3* points, uint32_t numPoints, float r)
{
    for (uint32_t i = 0; i < numPoints; ++i)
    {
        const glm::ivec3 bucket = getBucket(points[i], r);
        buckets[bucketKey(bucket)].push_back(i);
    }
}
```

And this is the libcuckoo version:

```
inline glm::ivec3 getBucket(const glm::vec3& p, float r) const
{
    return glm::ivec3(glm::floor((1.0f / r) * p));
}

cuckoohash_map<glm::ivec3, std::vector<uint32_t>> buckets;

HashGrid::HashGrid(const glm::vec3* points, uint32_t numPoints, float r)
{
    buckets.minimum_load_factor(0.0);   // for 0.01 exception: libcuckoo_load_factor_too_low

    #pragma omp parallel for schedule(dynamic, 100)
    for (uint32_t i = 0; i < numPoints; ++i)
    {
        const glm::ivec3 bucket = getBucket(points[i], r);

        buckets.upsert(bucket, [&](std::vector<uint32_t>& indices)
        {
            indices.push_back(i);
        });
    }
}
```

**Comment by tbiedert** [comment]
An update on this:

- 8.6 mio points:  construction 250ms, 1-2 GB RAM 

- 8.7 mio points:  'libcuckoo_load_factor_too_low' exception when default minimum load factor, or full RAM + swap consumption if minimum load factor = 0

**Comment by tbiedert** [comment]
Well, resolved the issue by increasing the number of slots per bucket to 32.

**Comment by dnbaker** [comment]
I've had similar issues which led me to use a different hash table. I'll have to try changing the number of slots per bucket myself.

**Comment by tbiedert** [comment]
There is another issue in my code I'd like to address:

In my construction code I use `upsert` to fill the buckets (vectors) of my hash grid:
```
    #pragma omp parallel for schedule(dynamic, 100)
    for (uint32_t i = 0; i < numPoints; ++i)
    {
        const glm::ivec3 bucket = this->getBucket(this->points[i]);

        this->buckets.upsert(bucket, [&](std::vector<uint32_t>& indices)
        {
            indices.push_back(i);
        });
    }
```

However, I realized the lambda is only called when the key already exists, and not when a new vector is inserted (as stated in the documentation).

For the time being I have resolved the issue by a quick hack: I simply always run the lambda in libcuckoo:

```
  template <typename K, typename F, typename... Args>
  bool uprase_fn(K &&key, F fn, Args &&... val) {
    hash_value hv = hashed_key(key);
    auto b = snapshot_and_lock_two<normal_mode>(hv);
    table_position pos = cuckoo_insert_loop<normal_mode>(hv, b, key);
    if (pos.status == ok) {
      add_to_bucket(pos.index, pos.slot, hv.partial, std::forward<K>(key),
                    std::forward<Args>(val)...);
      fn(buckets_[pos.index].mapped(pos.slot));  // <-- tb: HACK! always call lambda
    } else {
      if (fn(buckets_[pos.index].mapped(pos.slot))) {
        del_from_bucket(pos.index, pos.slot);
      }
    }
    return pos.status == ok;
  }
```

In the current API, is there a valid way of doing above without modifying the libcuckoo code?

Thanks!

**Comment by toojays** [comment]
@tbiedert, any additional arguments to ``upsert()`` after your update function are passed to the constructor of your map value. So you just need a way to construct (rather than update) the value you want. It looks like you should just be able to do like:
```c++
    #pragma omp parallel for schedule(dynamic, 100)
    for (uint32_t i = 0; i < numPoints; ++i)
    {
        const glm::ivec3 bucket = this->getBucket(this->points[i]);
        auto updater = [&](std::vector<uint32_t>& indices) { indices.push_back(i); };
        this->buckets.upsert(bucket, updater, 
                             /* If no existing value, upsert calls std::vector<uint32_t>::vector(1, i) */
                             1, i);
    }
```

**Comment by tbiedert** [comment]
Cool, thanks!

**Comment by dave-andersen** [comment]
Tim, I'm concerned the default hash function when applied to your datatype isn't producing values that are uniformly distributed.  This would result in a lot of bucket collisions (which you're resolving by increasing slots per bucket), and many unnecessary resizes because you'd often fill both alternative buckets.

I wonder if this is what's leading to your poor speed and memory use.   I don't understand the glm library well enough to say much smart here.  But I'd be tempted to see if you might change the hash function being used to hash a glm::ivec3 to something like...  <thinking>

uint64_t h = (ivec.1 << 32 | ivec.2) * 0xff51afd7ed558ccd;
h ^= (h << 41) | (h >> 23);
h += ivec.3;
h *= 0xc4ceb9fe1a85ec53;
h ^= (h << 41) | (h >> 23);
return h;

(basically just a murmur-inspired quick mix of the components.  Better would be actually using a stronger hash function, of course)

**Comment by tbiedert** [comment]
Hi Dave, thanks for your feedback!  I have tried your proposal without much success, as I had to increase the number of slots even more.

For a test data set with 3 million points:

(1) glm hasher, 4 slots:
- Build grid: 80ms
- Searches: 1572 ms

(2) Your hasher, 256 slots   (yes, I had to increase it that much)
- Build grid: 260 ms
- Searches: 6225 ms


Code looked like this:
```c++
    struct DaveHasher
    {
        uint64_t operator()(const glm::ivec3& v) const
        {
            uint64_t h = (((uint64_t) v.x) << 32 | v.y) * 0xff51afd7ed558ccd;
            h ^= (h << 41) | (h >> 23);
            h += v.z;
            h *= 0xc4ceb9fe1a85ec53;
            h ^= (h << 41) | (h >> 23);
            return h;
        }
    };

    cuckoohash_map<glm::ivec3, std::vector<uint32_t>,
            DaveHasher,
            std::equal_to<glm::ivec3>,
            std::allocator<std::pair<const glm::ivec3, std::vector<uint32_t>>>,
            256> buckets;
```

That's the glm implementation:
```c++
namespace glm {
namespace detail
{
	GLM_INLINE void hash_combine(size_t &seed, size_t hash)
	{
		hash += 0x9e3779b9 + (seed << 6) + (seed >> 2);
		seed ^= hash;
	}
}}

namespace std
{
	template <typename T, glm::precision P>
	GLM_FUNC_QUALIFIER size_t hash<glm::tvec3<T, P>>::operator()(glm::tvec3<T, P> const & v) const
	{
		size_t seed = 0;
		hash<T> hasher;
		glm::detail::hash_combine(seed, hasher(v.x));
		glm::detail::hash_combine(seed, hasher(v.y));
		glm::detail::hash_combine(seed, hasher(v.z));
		return seed;
	}
}
```

**Comment by dave-andersen** [comment]
Interesting!  Thanks for testing.  The one last thing I'd then try is a legitimately strong hash - CityHash is always a good one, but anything that's easy to install and test out from CityHash, FarmHash, or xxHash would be a good choice.

(The behavior of needing to add more buckets is strongly suggestive of seeing many hash collisions that aren't being resolved well by the table.)

I assume std::size_t is 64 bits on your system?  If not, the table will probably fall down miserably at 170M elements.

Finally .. this one is a bit ugly and untested.  It's possible that the partial_key size is too small for the number of elements you're trying to use.  Once you've tested with a strong hash function, if it still seems like you need to use a large bucket size, then you could try increasing the size of the partial key from a uint8_t to a uint16_t.  Then change the partial_key function (L721 of cuckoohash_map.hh) to return hash_16bit instead of hash_8bit.  In *theory*, though, 8 bits should be enough for up to 2^32 entries in the hash table...... in theory.
