### ISSUE TITLE
unable to compile with gcc for C example

### ISSUE THREAD

**Issue by mmanoj** [efficient/libcuckoo#99]
I'm try to compile c example with gcc. However I'm getting below error. Please advice to resolve it.

gcc -Wall -g -o c_hash c_hash.c -I/opt/libtest/libcuckoo/install/include -rdynamic -L -l/opt/libcuckoo/build/examples/libint_str_table.a -L -l/opt/libcuckoo/build/examples/libblob_blob_table.a -pthread -std=gnu99
/tmp/ccUwUNxK.o: In function `main':
/lib/c_hash.c:23: undefined reference to `int_str_table_init'
/lib/c_hash.c:28: undefined reference to `int_str_table_insert'
/lib/c_hash.c:39: undefined reference to `int_str_table_find'
/lib/c_hash.c:48: undefined reference to `blob_blob_table_init'
/lib/c_hash.c:52: undefined reference to `blob_blob_table_lock_table'
/lib/c_hash.c:74: undefined reference to `blob_blob_table_locked_table_insert'
/lib/c_hash.c:81: undefined reference to `blob_blob_table_locked_table_cbegin'
/lib/c_hash.c:83: undefined reference to `blob_blob_table_locked_table_cend'
/lib/c_hash.c:96: undefined reference to `blob_blob_table_const_iterator_key'
/lib/c_hash.c:97: undefined reference to `blob_blob_table_const_iterator_mapped'
/lib/c_hash.c:92: undefined reference to `blob_blob_table_const_iterator_increment'
/lib/c_hash.c:91: undefined reference to `blob_blob_table_const_iterator_equal'
/lib/c_hash.c:103: undefined reference to `blob_blob_table_const_iterator_free'
/lib/c_hash.c:104: undefined reference to `blob_blob_table_const_iterator_free'
/lib/c_hash.c:105: undefined reference to `blob_blob_table_locked_table_free'
/lib/c_hash.c:106: undefined reference to `blob_blob_table_free'
/lib/c_hash.c:107: undefined reference to `int_str_table_free'
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'hashtest' failed
make: *** [hashtest] Error 1

**Comment by manugoyal** [comment]
[output.txt](https://github.com/efficient/libcuckoo/files/1866536/output.txt)

Hey there! On my machine, compiling c_hash using CMake seems to work fine. I pasted the verbose output of my compilation for comparison. I'm not sure exactly how your directories are laid out, so it's hard to say exactly why it's not finding the functions, but it should work if done in a similar fashion to the CMake example.

**Comment by mmanoj** [comment]
Hi,

Thanks for the feedback, I try to build using gnu make file. Is there any example with gnu make. I'm not much families with CMake.

I want to integrate it with my C program and make file. Any advice highly appreciated.

Thank you,
Manoj M

**Comment by manugoyal** [comment]
Hi Manoj, unfortunately, we don't have a gnu make example in the repo, because that might be overly-specific to a particular build environment. CMake has the advantage of producing make files designed to work with your particular platform.

If you want to integrate with your own makefile-based project, I'd suggest building the examples with cmake within the `libcuckoo` repo, and looking at the actual commands the produced makefile runs. You can inspect this by running `make all VERBOSE=1`. These will probably resemble what I pasted in the `output.txt` file above. You might be able to compile in a similar way on your own machine to make it work.

Best,
Manu
